/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author malith
 */
public class RemainingDays extends javax.swing.JFrame {

    /**
     * Creates new form AddPatient
     */
    public RemainingDays() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnViewRemainigDaysCancel = new javax.swing.JButton();
        TxtViewRemainigDaysNicSearch = new javax.swing.JTextField();
        BtnViewRemainigDaysNicSearch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblViewRemainigDaysDetails = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Remaing Days");

        BtnViewRemainigDaysCancel.setBackground(new java.awt.Color(255, 0, 0));
        BtnViewRemainigDaysCancel.setForeground(new java.awt.Color(255, 255, 255));
        BtnViewRemainigDaysCancel.setText("Cancel");
        BtnViewRemainigDaysCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnViewRemainigDaysCancelMouseClicked(evt);
            }
        });

        BtnViewRemainigDaysNicSearch.setBackground(new java.awt.Color(102, 102, 255));
        BtnViewRemainigDaysNicSearch.setForeground(new java.awt.Color(255, 255, 255));
        BtnViewRemainigDaysNicSearch.setText("Search");
        BtnViewRemainigDaysNicSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewRemainigDaysNicSearchActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Enter NIC");

        TblViewRemainigDaysDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIC", "Name", "Admitted Date", "Quarantine Period", "Discharge Date"
            }
        ));
        jScrollPane1.setViewportView(TblViewRemainigDaysDetails);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TxtViewRemainigDaysNicSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnViewRemainigDaysNicSearch))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnViewRemainigDaysCancel)
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtViewRemainigDaysNicSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnViewRemainigDaysNicSearch)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnViewRemainigDaysCancel)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setForeground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnViewRemainigDaysCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnViewRemainigDaysCancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_BtnViewRemainigDaysCancelMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        insertDataToHeap();
        refreshTable();
    }//GEN-LAST:event_formWindowOpened

    private void insertDataToHeap()
    {
        ResultSet rs=db.selectData("select QuarantinePeriod as qp from tb_patient");
        try {
            while(rs.next())
            {
                minHeap.insert(rs.getInt("qp"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Warning...!",JOptionPane.WARNING_MESSAGE);
        }
    }
    minHeap minHeap = new minHeap((getHeapSize()+1));
    
    private int getHeapSize()
    {
        int size=0;
        ResultSet rs = new DatabaseController().selectData("select count(NIC) as count from tb_patient");
        try {
            while(rs.next())
            {
                size = rs.getInt("count");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        return size;
    }
    DatabaseController db = new DatabaseController();
    private void refreshTable()
    {
        DefaultTableModel tmodel = (DefaultTableModel)TblViewRemainigDaysDetails.getModel();
        tmodel.setRowCount(0);
        int[] values = minHeap.printView();
        for(int c=0;c<getHeapSize();c++)
        {
            if(values[c]!=0)
            {
                try {
                    ResultSet rs = db.selectData("select * from tb_patient where QuarantinePeriod = '"+String.valueOf(values[c])+"'");
                    while(rs.next())
                    {
                        String nic = rs.getString("NIC");
                        String name = rs.getString("Name");
                        String adDate = String.valueOf(rs.getDate("AdmittedDate"));
                        String qPeriod = String.valueOf(values[c]);
                        String disDate = String.valueOf(rs.getDate("DischargeDate"));
                        String[] tbData={nic,name,adDate,qPeriod,disDate};
                        tmodel.addRow(tbData);
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Unable to Load Details Refresh and Try Again","Error..!",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
    
    private void BtnViewRemainigDaysNicSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewRemainigDaysNicSearchActionPerformed
        // TODO add your handling code here:
        Pattern id = Pattern.compile("^([0-9]{9}[x|X|v|V]|[0-9]{12})$");
        Matcher mid = id.matcher(TxtViewRemainigDaysNicSearch.getText());
        
        if(TxtViewRemainigDaysNicSearch.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Patient NIC cannot be blank!","Warning!", JOptionPane.WARNING_MESSAGE);
        }
        else if(mid.matches()==false){
            JOptionPane.showMessageDialog(this,"Patient NIC is invalid. Please give valid NIC number!","Invalid NIC!", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            loadDataTable("Select * from tb_patient where NIC = '"+TxtViewRemainigDaysNicSearch.getText()+"'");
             if(TblViewRemainigDaysDetails.getRowCount()<=0)
                 {
                     JOptionPane.showMessageDialog(this, "Cannot Find Data","Warning",JOptionPane.WARNING_MESSAGE);
                    TxtViewRemainigDaysNicSearch.setText("");
                    loadDataTable("Select * from tb_patient");
                  }
        }
    }//GEN-LAST:event_BtnViewRemainigDaysNicSearchActionPerformed

    private void loadDataTable(String sql)
    {
        DefaultTableModel tmodel = (DefaultTableModel)TblViewRemainigDaysDetails.getModel();
        tmodel.setRowCount(0);
        DatabaseController db = new DatabaseController();
        ResultSet rs = db.selectData(sql);
        if(rs!=null)
        {
            try {
                while(rs.next())
                {
                    String nic = rs.getString("NIC");
                    String name = rs.getString("Name");
                    String adDate = String.valueOf(rs.getDate("AdmittedDate"));
                    String qPeriod = String.valueOf(rs.getInt("QuarantinePeriod"));
                    String disDate = String.valueOf(rs.getDate("DischargeDate"));
                    
                    String[] tbData = {nic,name,adDate,qPeriod,disDate};
                    
                    tmodel.addRow(tbData);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "An Error Occured While Loading Data", "Error..!", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Cannot Find Data","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemainingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemainingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemainingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemainingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemainingDays().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnViewRemainigDaysCancel;
    private javax.swing.JButton BtnViewRemainigDaysNicSearch;
    private javax.swing.JTable TblViewRemainigDaysDetails;
    private javax.swing.JTextField TxtViewRemainigDaysNicSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
