/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


/**
 *
 * @author malith
 */
public class UpdatePatient extends javax.swing.JFrame {

    /**
     * Creates new form AddPatient
     */
    public UpdatePatient() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtAddPatientNic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtAddPatientName = new javax.swing.JTextField();
        TxtAddPatientAdmittedDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        TxtAddPatientQperiodFromDate = new com.toedter.calendar.JDateChooser();
        TxtAddPatientQperiodToDate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        TxtAddPatientDischargeDate = new com.toedter.calendar.JDateChooser();
        BtnAddPatientCancel = new javax.swing.JButton();
        BtnAddPatientSave = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Patient Details");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("NIC");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Name");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Admitted Date");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("------------------------------------");
        jLabel5.setToolTipText("");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Discharge Date");

        TxtAddPatientAdmittedDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtAddPatientAdmittedDateMouseClicked(evt);
            }
        });
        TxtAddPatientAdmittedDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TxtAddPatientAdmittedDatePropertyChange(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("From");

        TxtAddPatientQperiodFromDate.setEnabled(false);

        TxtAddPatientQperiodToDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TxtAddPatientQperiodToDatePropertyChange(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("To");

        TxtAddPatientDischargeDate.setEnabled(false);

        BtnAddPatientCancel.setBackground(new java.awt.Color(255, 0, 0));
        BtnAddPatientCancel.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddPatientCancel.setText("Cancel");
        BtnAddPatientCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAddPatientCancelMouseClicked(evt);
            }
        });
        BtnAddPatientCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddPatientCancelActionPerformed(evt);
            }
        });

        BtnAddPatientSave.setBackground(new java.awt.Color(102, 102, 255));
        BtnAddPatientSave.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddPatientSave.setText("Save");
        BtnAddPatientSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddPatientSaveActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Quarantine Period ");
        jLabel9.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnAddPatientSave)
                                .addGap(18, 18, 18)
                                .addComponent(BtnAddPatientCancel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtAddPatientDischargeDate, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(TxtAddPatientQperiodToDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtAddPatientAdmittedDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtAddPatientName)
                                    .addComponent(TxtAddPatientNic)
                                    .addComponent(TxtAddPatientQperiodFromDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtAddPatientNic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TxtAddPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtAddPatientAdmittedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtAddPatientQperiodFromDate, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtAddPatientQperiodToDate, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtAddPatientDischargeDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAddPatientCancel)
                    .addComponent(BtnAddPatientSave))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setForeground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddPatientCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddPatientCancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_BtnAddPatientCancelMouseClicked

    private void BtnAddPatientSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddPatientSaveActionPerformed
        // TODO add your handling code here:
        
        Pattern name = Pattern.compile("^[a-zA-Z ]*$");
        Matcher mname = name.matcher(TxtAddPatientName.getText());
        
        if(TxtAddPatientName.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Patient name cannot be blank!","Warning!", JOptionPane.WARNING_MESSAGE);
        }
        else if(mname.matches()==false){
            JOptionPane.showMessageDialog(this,"Its does not like a name!","Invalid Name!", JOptionPane.ERROR_MESSAGE);
        }
         else if(TxtAddPatientAdmittedDate.getDate()==null){
                        JOptionPane.showMessageDialog(this,"Admitted Date cannot be blank!","Warning!", JOptionPane.WARNING_MESSAGE);
        }
        else if(TxtAddPatientQperiodToDate.getDate()==null){
                         JOptionPane.showMessageDialog(this,"What's about the date this patient can exit?","Warning!", JOptionPane.WARNING_MESSAGE);

        }
        else{
            
            
        Date admittedDate = TxtAddPatientAdmittedDate.getDate();
        Date dischargeDate = TxtAddPatientDischargeDate.getDate();
        DateFormat dateformat =new SimpleDateFormat("yyyy-MM-dd");
        DatabaseController db = new DatabaseController();
        int i = db.insertUpdateDelete("update tb_patient set Name = '"+TxtAddPatientName.getText()+"',AdmittedDate='"+dateformat.format(admittedDate)+"',QuarantinePeriod='"+jLabel5.getText()+"',DischargeDate='"+dateformat.format(dischargeDate)+"'"
                + "where NIC='"+TxtAddPatientNic.getText()+"'");
        if(i==1)
            JOptionPane.showMessageDialog(this, "Patient Details Added Successfully","Done..!",JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Something Went Wrong While Saving Data","Error..!",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_BtnAddPatientSaveActionPerformed

    private void TxtAddPatientAdmittedDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtAddPatientAdmittedDateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAddPatientAdmittedDateMouseClicked

    private void TxtAddPatientAdmittedDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TxtAddPatientAdmittedDatePropertyChange
        // TODO add your handling code here:
        if(TxtAddPatientAdmittedDate.getDate()!=null)
        {
            Date date = TxtAddPatientAdmittedDate.getDate();
            TxtAddPatientQperiodFromDate.setDate(date);
        }
        else
        {
            TxtAddPatientQperiodFromDate.setDate(null);
        }
    }//GEN-LAST:event_TxtAddPatientAdmittedDatePropertyChange

    private void TxtAddPatientQperiodToDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TxtAddPatientQperiodToDatePropertyChange
        // TODO add your handling code here:
        if(TxtAddPatientQperiodToDate.getDate()!=null)
        {
            Date date = TxtAddPatientQperiodToDate.getDate();
            TxtAddPatientDischargeDate.setDate(date);
        }
        else
        {
            TxtAddPatientDischargeDate.setDate(null);
        }
        if(TxtAddPatientQperiodToDate.getDate()!=null && TxtAddPatientAdmittedDate.getDate()!=null)
        {
            Date fromDate = TxtAddPatientQperiodFromDate.getDate();
            Date toDate = TxtAddPatientQperiodToDate.getDate();
            DateFormat dateformat =new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
            String from = dateformat.format(fromDate);
            String to = dateformat.format(toDate);                     
            jLabel5.setText(findDifference(from,to));
        }
        else
        {
            jLabel5.setText("------------------------------------");
        }
    }//GEN-LAST:event_TxtAddPatientQperiodToDatePropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Pattern id = Pattern.compile("^([0-9]{9}[x|X|v|V]|[0-9]{12})$");
        Matcher mid = id.matcher(TxtAddPatientNic.getText());
        
        if(TxtAddPatientNic.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Patient NIC cannot be blank!","Warning!", JOptionPane.WARNING_MESSAGE);
        }
        else if(mid.matches()==false){
            JOptionPane.showMessageDialog(this,"Patient NIC is invalid. Please give valid NIC number!","Invalid NIC!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            
            DatabaseController db = new DatabaseController();
        ResultSet rs = db.selectData("Select * from tb_patient where NIC = '"+TxtAddPatientNic.getText()+"'");
        if(rs!=null)
        {
            try {
                while(rs.next())
                {
                    TxtAddPatientNic.setText(rs.getString("NIC"));
                    TxtAddPatientName.setText(rs.getString("Name"));
                    jLabel5.setText(String.valueOf(rs.getInt("QuarantinePeriod")));
                    TxtAddPatientAdmittedDate.setDate(rs.getDate("AdmittedDate"));
                    TxtAddPatientDischargeDate.setDate(rs.getDate("DischargeDate"));
                    TxtAddPatientQperiodToDate.setDate(TxtAddPatientDischargeDate.getDate());
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error Occured while loading the data","Error..!",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No Data Found","Warning..!",JOptionPane.WARNING_MESSAGE);
        }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnAddPatientCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddPatientCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAddPatientCancelActionPerformed

    private String findDifference(String start_date, String end_date)
    {
        String days="";
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        try {
            Date d1 = sdf.parse(start_date);
            Date d2 = sdf.parse(end_date);
            
            long difference_In_Time = d2.getTime() - d1.getTime();
  
            long difference_In_Seconds = (difference_In_Time/ 1000)% 60;
  
            long difference_In_Minutes = (difference_In_Time/ (1000 * 60))% 60;
  
            long difference_In_Hours = (difference_In_Time/ (1000 * 60 * 60))% 24;
  
            long difference_In_Years = (difference_In_Time / (1000l * 60 * 60 * 24 * 365));
  
            long difference_In_Days = (difference_In_Time / (1000 * 60 * 60 * 24)) % 365; 
            
            days= String.valueOf(difference_In_Days);
        }
        catch (ParseException e) {
            e.printStackTrace();
        }
        return days;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddPatientCancel;
    private javax.swing.JButton BtnAddPatientSave;
    private com.toedter.calendar.JDateChooser TxtAddPatientAdmittedDate;
    private com.toedter.calendar.JDateChooser TxtAddPatientDischargeDate;
    private javax.swing.JTextField TxtAddPatientName;
    private javax.swing.JTextField TxtAddPatientNic;
    private com.toedter.calendar.JDateChooser TxtAddPatientQperiodFromDate;
    private com.toedter.calendar.JDateChooser TxtAddPatientQperiodToDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
